# This file should be placed in ~/.config/dynamic-hyprlive/ directory (by default)
#
# Hello this is where you will configure what games, openrgb profiles and wallpapers to display, In the event of an error or missing wallpapers its best to check the formatting of this config!
# Note that between each item is a TAB, HOWEVER if you want a variety of wallpapers for ONE game each wallpaper should be seperated by a SPACE after the initial first one
# You can also specify a subdirectory instead of multiple wallpapers by using the directory name followed by ".dir" (e.g. Zenless.dir)
#
# To set the default wallpaper, use "DEFAULT" as the process or game name
# * If openrgb is not being used simply type "n/a"
# Format is as follows: Game.exe(or Process name)	Openrgb-Profile     Wallpaper1 Wallpaper2 Wallpaper3 ... 
#
# DEFAULT	beckford-night	ROSCAELIFER.dir
#

